version: '3.8'
services:
  stream-camera:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stream-camera
    volumes:
      - /dev:/dev
    ports:
      - 8555:8555
    environment:
      - SUFFIX 1
      - RABBITMQ_URL amqp://guest:guest@rabbitmq:5672/famanager
      - QUEUE_ORIGIN stream-usb-video-by-rtsp-multiple-camera-queue
      - QUEUE_TO template-matching-by-opencv-for-rtsp-queue
      - SCALE 1
      - DISPLAY
    tty: true